temp changes
Signed-off-by: Gabriel Ionescu <gbi@amazon.com>

diff --git a/tools/devtool b/tools/devtool
--- a/tools/devtool
+++ b/tools/devtool
@@ -72,7 +72,7 @@
 DEVCTR_IMAGE_NO_TAG="public.ecr.aws/firecracker/fcuvm"
 
 # Development container tag
-DEVCTR_IMAGE_TAG="v31"
+DEVCTR_IMAGE_TAG="latest"
 
 # Development container image (name:tag)
 # This should be updated whenever we upgrade the development container.
@@ -342,9 +342,12 @@ cmd_build_devctr() {
     done
 
     docker build -t "$DEVCTR_IMAGE_NO_TAG" -f "$FC_DEVCTR_DIR/$docker_file_name" $build_args .
+    ret=$?                                             
+    [ $ret -ne 0 ] && die "Error building Dockerfile."
 
     if [ "$should_update_python_packages" = true ]; then
         update_python_package_version
+        [ $ret -ne 0 ] && die "Error building Dockerfile."
     fi
 }
 
